---
- hosts: all
  become: yes
  tasks:
  - name: i want to install apache2 webserver on ubuntu ansible node
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian" 
  - name: i want to start apache2 webserver on ubuntu ansible node
    service:
      name: apache2
      state: started
    when: ansible_os_family=="Debian"

  - name: install httpd webserver on redhat ansible node
    dnf:
      name: httpd
      state: present

  - name: start webserver on redhat ansible node
    service:
      name: httpd
      state: started
    when: ansible_os_family=="Redhat"      